server:
  port: 9992 # 端口

spring:
  application:
    name: uncg-mail # 应用名称
  #数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_uncg?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: '{cipher}AQBl1a8pv4XhJXY9mucPKovthP8E07JfespEEop2Yl4a29GO4ybenMQgG19szQ4uw4Y551gfbrhUthjXM9NPH2nyoKimrVLrZOks5xRBX8lhHRv4xuOLHEmpgTnxnQUzUQTkStqPbP07M9rZMWVzWI4feP44vQADYCC5x15lbEIVKuMCrbERtVKUM3ftD4Ax3lqGVklO9nRPmFSPOOT5rUMoTagep/b6lacQtHyy6KubszvoXuQqWZCmtZEKdn9Sc1pdU+fiSPsbCwgCVTJ+7Z9fs9LTJEbAL9CCUdTMSUSion6aEnLA0yDyIEghyTFNRganOvSm4nQnT8+fenYEvBjsjlWz1ueokPOVkvdKmawELqSKbZ6rN7ee1gCfwA0axDs='
    password: '{cipher}AQAQvxgxulehCa78EWu7Ojl5YS8M18NAF7zMhciobqWSJyJj4Jv3WB5b28ENTSnNCoImSrRBjahQQbGhZtwHqZAWsjE24nIlobVeWmXYt+yVh67Cb2G/ln/aoVz+T5oRCfjdthAfXom8pBXY3e7ZpjqtHLnSSLuDCeNJh1uumKqpYVoDeIzaBaGCQZFn0g4j9aWCgT8CFeUWbqaAGYv0Ol9Bc5n8pTMqmnEX9K/8KumS9Oosl9ikSEc2/AC58F5pRNX9MnwoXTULy1jqL2TNt7BMp+jgtLfQMm8nZxmOhGZy8u0T7aJ6l4u7iFndPDrOEd7bxhN2mqo39/N0O4ZBzH3JnTx/qI0VmpdM64cf6m32Cr6APk3LuRjo2NFlJjfTlNM='
  #jpa配置
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: '{cipher}AQA70sEHeRoFiy1iXIhFdo7NshhhsmbIuB3O5P46SJIhH1pzsSy5D17So9IwshqDK3rfA0qfVP5Qv5d27FEjRo/tL7ge4rMYYdctEIsvmJ3a0qN+AwTxyZ9Ym11cveLXnoqQDHU8Yhz/tjzgZXb8M969xJyHtpRbxenEYtQ98bXUjaF5QifDGFVxA8fauitNRWQlOQ2V2QO5cFh80bgYe9bKqQGET0l0Amq0WFEPizZAFQYj9uTzqR0KxQWxqT3xDz1cnz9C5kO1HJOdgRhWUQYe3TH3rdlB882grVo6mBk+kWF782Lx6qa177BFROPgckGaEh4MGZsnTKw+oHnXXpbb7Vhkhx4O0VQ4eS1WroiHnCFoHXXxkVHXBXYDpS9A/s4='
  mail:
    host: smtp.qq.com
    username: '{cipher}AQAwDldE0OiLpX7ZSf54PJFxKRR9tFclzGUYKF9cwTCxIk1T9oUQ1Ky61qZJ3UM5hXtg0OKN67LTOXx5bOWVshjiiPSn3GFUETalVJiN3ahbO4nGFTcJepqUSdVOWwZJGmfBOily5pPcuV5mE21BAqg6uQpdphLofalFAy/8VPnzISJXTF0jueAXIBhaHDjvapFA8hAYf+PWRfPOX00Fmz3bdPc8GP2u5FUodK/9MlCfDpwrLYsrqmx5ORZqeUxhsuluPzuAGZ8/JmrSx4P2Ok7jYTH5vgc/aVcic/Sa64G369GGk8Y5X+HM8zKuWiqrG3cqPsMVI4Lg7oi3qQ7nWE9tGzrGqiEvaZrHG6NsgPH5fUzR8hgL2OSaiznKN24Ru32LoDAOY96TgBP4ZyQAC2Jb'
    password: '{cipher}AQBAFmFm4ihQSLUORsScpJyiOg0xBFgMKrImuzUp7A/WH5nEEPOo4vnMK/uq1wpJhfdr2cyurKFTqE2clMoJ5HnBIH/PmSu8QK64zvl1+xQ7GFOyjrL8alqBHuqkgywuWsrGqTM9UYPqImog0CMSNXOFMDZ+Utubm+3W9b4dnRyFx5nkmDn6RafMtEcwwDFzP3x0MFx3Mh4WSaCiuCgHsACfXgip1Xv4AAucVvoo+oKxa7xC9f8ZioomDs36F6FYFu2/lYcSF8TuVh5wqkRD+2Qcq9TdGi+d4c+usg8t0u7tBMT54kHEusfXSLIFRSThQ3vl4BRKDQ182pew5eDK+EEk3uUQGaqlxAftcOjKL5N9G0hVEwHra91wRoq+6CupLJNiwcjTvvsSJpOqjc083fm9'
    default-encoding: UTF-8

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true       # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    service-url:                  # 设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

# 自定义配置
name: uncg-mail-dev-v1.0
password: '{cipher}AQBb95lBLRyMrmByfQ/t8fhUkeJqTDsfMBvYF7mDujqPtydPNEtRRTTGrCmmg/tCkaGP5xEIiKetD6hju6wb57rdCheL4IuO3Nvwl6O0BbqwLpzkWQ7g/pn7Yg8yy1RCtRcJp0gUoW0AtIv6Gm9qEUw6VO0+HXQwC3GIEaBMB+sGfhFTk8DiAT+DFMaAIJdhkqj+lJWzfT4OOTOLC302SSN29aMB1H3ejeT+/180B5dPKaoPXAq+Zv+MYdMfywIFjU9E8EbxNhJH7AVF3J3PgIyAbNKJcfr63b3/tMHxOjqZpyrJhy9E+FfhraCtRnWAxgjxssZTXS1yppyPd8OnI6nVFZZiJq8AOqLHmYRZeja0DD4+OWG5VuWMJ2rU6ahioPE='
